import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[shell]
program = "zsh"
args = ["-l"]

[window]
decorations = "Buttonless"
opacity = 0.9
blur = true
startup_mode = "Maximized"

[font]
size = 14

[font.offset]
x = 0 
y = 0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[colors]
draw_bold_text_with_bright_colors = true
