# Disable the blank line at the start of the prompt
add_newline = false

right_format = ''

format = """
$directory\
$git_branch\
$git_commit\
$git_stage\
$git_metrics\
$git_status\
$nodejs\
$ruby\
$memory_usage\
$battery\
$time\
$status"""

